name = input("Enter your name: ")
age = int(input("Enter your age: "))
language = input("Enter your favorite language: ")

print("=========================")
print("      MY INFO CARD")
print("=========================")
print("Name    :", name)
print("Age     :", age)
print("Language:", language)
print("=========================")